# Generated by Django 6.0.6 on 2026-06-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('shop_name', models.CharField(max_length=100)),
                ('region', models.CharField(default='OTHER', max_length=10)),
                ('create_time', models.DateTimeField(null=True)),
                ('created_hours', models.FloatField(default=0)),
                ('logistics_no', models.CharField(blank=True, max_length=100, null=True)),
                ('fulfillment_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delay_risk', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
